apiVersion: apps/v1
kind: Deployement
metadata:
  name: deployment
spec:
  selector:
    matchLables:
      app: react-apps
    replicate : 1
    template:
      metedata:
        labels:
          app: react-app
      spec:
        containers:
          - name: react-app
            image: fabien123/jenkins_project:latest

---
apiVersion: v1
kind: Service
metadata: 
  name: my-react-app-srv
spec: 
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000