---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-react
 labels:
  app: myapp-react
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp-react
 template:
  metadata: 
   labels:
    app: myapp-react
  spec:
   containers:
   - name: myapp-react
     image: fabien123/jenkins_project:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-react
spec:
  type: LoadBalancer
  selector:
    app: myapp-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080