apiVersion: apps/v1
kind: Deployment
metadata:
name: deployment
labels:
  app: myreact-app
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: myreact-app
      tier: myreact-app
  spec:
    containers:
    - name: myreact-app
      image: fabien123/jenkins_project:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: myreact-app

---
apiVersion: v1
kind: Service
metadata:
name: myreact-app
labels:
  app: myreact-app
spec:
ports:
  - port: 3000
    targetPort: 3000
selector:
  app: myreact-app
  tier: myreact-app
type: LoadBalancer