---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: fabien123/jenkins_project:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
name: hello
labels:
  app: hello
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: hello
  tier: hello
type: LoadBalancer